version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/frontend_react
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /frontend
    target-branch: develop
    schedule:
      interval: weekly
