services:

  frontend_service:
    container_name: frontend_container
    build: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/certificate.crt:/etc/nginx/ssl/certificate.crt:ro
      - ./ssl/certificate.key:/etc/nginx/ssl/certificate.key:ro
